
services:
  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-db:/data/db
    networks:
      - app-network

  boot-app:
    image: igr/chatback:latest
    build:
      context: .
      dockerfile: DockerFile
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/chatapp
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo-db:

networks:
  app-network:
