FROM amd64/openjdk:21-jdk-slim

WorkDIR /app

COPY target/ChatAppBackend-0.0.1-SNAPSHOT.jar app.jar
# D:\java\ChatApp\ChatAppBackend\target\ChatAppBackend-0.0.1-SNAPSHOT.jar
Expose 8080

ENTRYPOINT ["java","-jar","app.jar"]